language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ccmikechen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ccmikechen/docker-react yarn test
